### ISSUE TITLE
Create filters in grafana to support subgroups views of apps

### ISSUE THREAD

**Issue by weshayutin** [dora-metrics/pelorus#964]
## Fix

Today, its only possible to view applications monitored by Pelorus in Grafana in 2 ways:
- individually
- all together

Users want to be able to have more options of view, like:
- hierarchically
- by cluster
- etc

## Requirements

- [ ] document new behavior
- [ ] allow new behavior to be configured by any number of levels of view

**Comment by mateusoliveira43** [comment]
Current ideas

- ✅ Tell user to add application name (app label in Prometheus) as a folder structure (ex.: `group/subgroup/name`) (or other separator, instead of `/`). Each level MUST have UNIQUE name to work properly. This should backwards compatible, i.e., adding just name, works as it previously worked

- ❌ Get the levels in Grafana dropdown (Application dropdown in by_app view) (ex.:  `group`, `subgroup` and `name`) (value `$app` in the queries)
  - OPTIONAL add `all` option (or something like this) to have just one Grafana dashboard

- ✅ Run queries in Grafana using https://prometheus.io/docs/prometheus/latest/querying/basics/#instant-vector-selectors ex.:
  ```
  deploy_timestamp{app=~".*$app.*"}
  ```
